// Code generated by protoc-gen-go. DO NOT EDIT.
// source: labeler.proto

package labeler

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Label struct {
	Node                 string   `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Label) Reset()         { *m = Label{} }
func (m *Label) String() string { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()    {}
func (*Label) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f7992ba896eeca0, []int{0}
}

func (m *Label) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Label.Unmarshal(m, b)
}
func (m *Label) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Label.Marshal(b, m, deterministic)
}
func (m *Label) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Label.Merge(m, src)
}
func (m *Label) XXX_Size() int {
	return xxx_messageInfo_Label.Size(m)
}
func (m *Label) XXX_DiscardUnknown() {
	xxx_messageInfo_Label.DiscardUnknown(m)
}

var xxx_messageInfo_Label proto.InternalMessageInfo

func (m *Label) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *Label) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type NodeInfo struct {
	Info                 string   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f7992ba896eeca0, []int{1}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*Label)(nil), "labeler.Label")
	proto.RegisterType((*NodeInfo)(nil), "labeler.NodeInfo")
}

func init() { proto.RegisterFile("labeler.proto", fileDescriptor_5f7992ba896eeca0) }

var fileDescriptor_5f7992ba896eeca0 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x49, 0x4c, 0x4a,
	0xcd, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x0c, 0xb9,
	0x58, 0x7d, 0x40, 0x4c, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xfc, 0x94, 0x54, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0xce, 0x20, 0x30, 0x5b, 0x48, 0x84, 0x8b, 0x15, 0xac, 0x4e, 0x82, 0x09, 0x2c, 0x08, 0xe1,
	0x28, 0xc9, 0x71, 0x71, 0xf8, 0xe5, 0xa7, 0xa4, 0x7a, 0xe6, 0xa5, 0xe5, 0x83, 0x74, 0x65, 0xe6,
	0xa5, 0xe5, 0xc3, 0x74, 0x81, 0xd8, 0x46, 0x4e, 0x5c, 0x7c, 0x3e, 0x10, 0xd3, 0x83, 0x53, 0x8b,
	0xca, 0x32, 0x93, 0x53, 0x85, 0x0c, 0xb8, 0x38, 0xc1, 0x22, 0x20, 0x6d, 0x42, 0x7c, 0x7a, 0x30,
	0xa7, 0x80, 0xc5, 0xa4, 0x04, 0xe1, 0x7c, 0x98, 0xa9, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x67, 0x1a,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x99, 0x8d, 0xfe, 0x87, 0xb7, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LabelerServiceClient is the client API for LabelerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LabelerServiceClient interface {
	LabelNode(ctx context.Context, in *Label, opts ...grpc.CallOption) (*NodeInfo, error)
}

type labelerServiceClient struct {
	cc *grpc.ClientConn
}

func NewLabelerServiceClient(cc *grpc.ClientConn) LabelerServiceClient {
	return &labelerServiceClient{cc}
}

func (c *labelerServiceClient) LabelNode(ctx context.Context, in *Label, opts ...grpc.CallOption) (*NodeInfo, error) {
	out := new(NodeInfo)
	err := c.cc.Invoke(ctx, "/labeler.LabelerService/LabelNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LabelerServiceServer is the server API for LabelerService service.
type LabelerServiceServer interface {
	LabelNode(context.Context, *Label) (*NodeInfo, error)
}

// UnimplementedLabelerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLabelerServiceServer struct {
}

func (*UnimplementedLabelerServiceServer) LabelNode(ctx context.Context, req *Label) (*NodeInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LabelNode not implemented")
}

func RegisterLabelerServiceServer(s *grpc.Server, srv LabelerServiceServer) {
	s.RegisterService(&_LabelerService_serviceDesc, srv)
}

func _LabelerService_LabelNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Label)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabelerServiceServer).LabelNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/labeler.LabelerService/LabelNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabelerServiceServer).LabelNode(ctx, req.(*Label))
	}
	return interceptor(ctx, in, info, handler)
}

var _LabelerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "labeler.LabelerService",
	HandlerType: (*LabelerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LabelNode",
			Handler:    _LabelerService_LabelNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "labeler.proto",
}
