// Code generated by protoc-gen-go. DO NOT EDIT.
// source: labeler.proto

package labeler

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeLabel struct {
	Node                 string   `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	KubeConfig           string   `protobuf:"bytes,3,opt,name=kubeConfig,proto3" json:"kubeConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeLabel) Reset()         { *m = NodeLabel{} }
func (m *NodeLabel) String() string { return proto.CompactTextString(m) }
func (*NodeLabel) ProtoMessage()    {}
func (*NodeLabel) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f7992ba896eeca0, []int{0}
}

func (m *NodeLabel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeLabel.Unmarshal(m, b)
}
func (m *NodeLabel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeLabel.Marshal(b, m, deterministic)
}
func (m *NodeLabel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeLabel.Merge(m, src)
}
func (m *NodeLabel) XXX_Size() int {
	return xxx_messageInfo_NodeLabel.Size(m)
}
func (m *NodeLabel) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeLabel.DiscardUnknown(m)
}

var xxx_messageInfo_NodeLabel proto.InternalMessageInfo

func (m *NodeLabel) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *NodeLabel) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *NodeLabel) GetKubeConfig() string {
	if m != nil {
		return m.KubeConfig
	}
	return ""
}

type PodLabel struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod                  string   `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Label                string   `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	KubeConfig           string   `protobuf:"bytes,4,opt,name=kubeConfig,proto3" json:"kubeConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodLabel) Reset()         { *m = PodLabel{} }
func (m *PodLabel) String() string { return proto.CompactTextString(m) }
func (*PodLabel) ProtoMessage()    {}
func (*PodLabel) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f7992ba896eeca0, []int{1}
}

func (m *PodLabel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodLabel.Unmarshal(m, b)
}
func (m *PodLabel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodLabel.Marshal(b, m, deterministic)
}
func (m *PodLabel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodLabel.Merge(m, src)
}
func (m *PodLabel) XXX_Size() int {
	return xxx_messageInfo_PodLabel.Size(m)
}
func (m *PodLabel) XXX_DiscardUnknown() {
	xxx_messageInfo_PodLabel.DiscardUnknown(m)
}

var xxx_messageInfo_PodLabel proto.InternalMessageInfo

func (m *PodLabel) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PodLabel) GetPod() string {
	if m != nil {
		return m.Pod
	}
	return ""
}

func (m *PodLabel) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *PodLabel) GetKubeConfig() string {
	if m != nil {
		return m.KubeConfig
	}
	return ""
}

type Info struct {
	Info                 string   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f7992ba896eeca0, []int{2}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeLabel)(nil), "labeler.NodeLabel")
	proto.RegisterType((*PodLabel)(nil), "labeler.PodLabel")
	proto.RegisterType((*Info)(nil), "labeler.Info")
}

func init() { proto.RegisterFile("labeler.proto", fileDescriptor_5f7992ba896eeca0) }

var fileDescriptor_5f7992ba896eeca0 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0x5d, 0x4b, 0x85, 0x40,
	0x14, 0xcc, 0xb4, 0x72, 0x0f, 0x18, 0x75, 0xe8, 0x41, 0x24, 0x22, 0x7c, 0xea, 0x49, 0xa2, 0x7e,
	0x42, 0x4f, 0x81, 0x84, 0x14, 0xfd, 0x00, 0x75, 0x8f, 0x21, 0x79, 0xf7, 0x2c, 0x7b, 0x3f, 0x7e,
	0xff, 0x65, 0x57, 0x57, 0x2f, 0xc8, 0x7d, 0x3b, 0x33, 0x73, 0x98, 0x61, 0x06, 0x92, 0xa1, 0x6e,
	0x68, 0x20, 0x53, 0x68, 0xc3, 0x3b, 0xc6, 0x9b, 0x09, 0xe6, 0xbf, 0x20, 0xbe, 0x58, 0x52, 0x69,
	0x21, 0x22, 0x44, 0x8a, 0x25, 0xa5, 0xc1, 0x73, 0xf0, 0x22, 0xbe, 0xdd, 0x8d, 0x0f, 0x70, 0xe5,
	0x7e, 0xd3, 0x4b, 0x47, 0x8e, 0x00, 0x9f, 0x00, 0xfe, 0xf7, 0x0d, 0x7d, 0xb0, 0xea, 0xfa, 0xbf,
	0x34, 0x74, 0xd2, 0x09, 0x93, 0x6b, 0x88, 0x2b, 0x96, 0xa3, 0xeb, 0x23, 0x08, 0x55, 0x6f, 0x68,
	0xab, 0xeb, 0xd6, 0x5b, 0x2f, 0x04, 0xde, 0x41, 0xa8, 0x59, 0x4e, 0xee, 0xf6, 0x5c, 0x12, 0xc3,
	0xf3, 0x89, 0xd1, 0x2a, 0x31, 0x83, 0xe8, 0x53, 0x75, 0x6c, 0x3b, 0xf4, 0xaa, 0x63, 0xdf, 0xc1,
	0xde, 0x6f, 0x06, 0x6e, 0xcb, 0xb1, 0xef, 0x0f, 0x99, 0x43, 0xdf, 0x12, 0xbe, 0x82, 0x70, 0x8c,
	0xed, 0x8e, 0x58, 0xf8, 0x71, 0xe6, 0x29, 0xb2, 0x64, 0xe6, 0xac, 0x6b, 0x7e, 0x81, 0x05, 0xc4,
	0x4e, 0xa9, 0x58, 0xe2, 0xfd, 0x2c, 0xfa, 0x92, 0xab, 0xff, 0xe6, 0xda, 0x0d, 0xfd, 0x7e, 0x0c,
	0x00, 0x00, 0xff, 0xff, 0x56, 0x2a, 0x65, 0x29, 0x79, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LabelerServiceClient is the client API for LabelerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LabelerServiceClient interface {
	LabelNode(ctx context.Context, in *NodeLabel, opts ...grpc.CallOption) (*Info, error)
	LabelPod(ctx context.Context, in *PodLabel, opts ...grpc.CallOption) (*Info, error)
}

type labelerServiceClient struct {
	cc *grpc.ClientConn
}

func NewLabelerServiceClient(cc *grpc.ClientConn) LabelerServiceClient {
	return &labelerServiceClient{cc}
}

func (c *labelerServiceClient) LabelNode(ctx context.Context, in *NodeLabel, opts ...grpc.CallOption) (*Info, error) {
	out := new(Info)
	err := c.cc.Invoke(ctx, "/labeler.LabelerService/LabelNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labelerServiceClient) LabelPod(ctx context.Context, in *PodLabel, opts ...grpc.CallOption) (*Info, error) {
	out := new(Info)
	err := c.cc.Invoke(ctx, "/labeler.LabelerService/LabelPod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LabelerServiceServer is the server API for LabelerService service.
type LabelerServiceServer interface {
	LabelNode(context.Context, *NodeLabel) (*Info, error)
	LabelPod(context.Context, *PodLabel) (*Info, error)
}

// UnimplementedLabelerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLabelerServiceServer struct {
}

func (*UnimplementedLabelerServiceServer) LabelNode(ctx context.Context, req *NodeLabel) (*Info, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LabelNode not implemented")
}
func (*UnimplementedLabelerServiceServer) LabelPod(ctx context.Context, req *PodLabel) (*Info, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LabelPod not implemented")
}

func RegisterLabelerServiceServer(s *grpc.Server, srv LabelerServiceServer) {
	s.RegisterService(&_LabelerService_serviceDesc, srv)
}

func _LabelerService_LabelNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeLabel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabelerServiceServer).LabelNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/labeler.LabelerService/LabelNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabelerServiceServer).LabelNode(ctx, req.(*NodeLabel))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabelerService_LabelPod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodLabel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabelerServiceServer).LabelPod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/labeler.LabelerService/LabelPod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabelerServiceServer).LabelPod(ctx, req.(*PodLabel))
	}
	return interceptor(ctx, in, info, handler)
}

var _LabelerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "labeler.LabelerService",
	HandlerType: (*LabelerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LabelNode",
			Handler:    _LabelerService_LabelNode_Handler,
		},
		{
			MethodName: "LabelPod",
			Handler:    _LabelerService_LabelPod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "labeler.proto",
}
