apiVersion: v1
kind: ServiceAccount
metadata:
  name: labeler-account
  namespace: labeler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labeler-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: labeler-role-binding
subjects:
- kind: ServiceAccount
  name: labeler-account
  namespace: labeler
roleRef:
  kind: ClusterRole
  name: labeler-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: labeler-pod
  namespace: labeler
  labels:
    app.kubernetes.io/name: labeler  
spec:
  terminationGracePeriodSeconds: 30
  serviceAccountName: labeler-account
  containers:
  - name: labeler-container
    image: tzourhs/labeler:1.4
    env:
    command: ["/labeler/bin/main"]
    args: []
    ports:
    - name: labeler-port
      containerPort: 9000
