apiVersion: v1
kind: Service
metadata:
  name: labeler-svc
  namespace: labeler
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30000
  selector:
    app.kubernetes.io/name: labeler