apiVersion: v1
kind: ServiceAccount
metadata:
  name: labeler-account
  namespace: labeler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labeler-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: labeler-role-binding
subjects:
- kind: ServiceAccount
  name: labeler-account
  namespace: labeler
roleRef:
  kind: ClusterRole
  name: labeler-role
  apiGroup: rbac.authorization.k8s.io
