apiVersion: v1
kind: Pod
metadata:
  name: labeler-pod
  namespace: labeler
  labels:
    app.kubernetes.io/name: labeler  
spec:
  terminationGracePeriodSeconds: 30
  serviceAccountName: labeler-account
  containers:
  - name: labeler-container
    image: tzourhs/labeler:1.1
    env:
    command: ["/labeler/bin/main"]
    args: []
    ports:
    - name: labeler-port
      containerPort: 9000
